sudo: required

services:
   docker

language: java
jdk: openjdk8

after_success:
   # Login Docker Hub
   - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
   
   # Build Image & Push to Docker Hub
   # Config Server
   - export CONFIG=continuestudying/limits-config
   - docker build -t $CONFIG ./spring-cloud-config-server
   - docker push $CONFIG
   
   # Eureka Naming Server
   - export EUREKA=continuestudying/limits-eureka
   - docker build -t $EUREKA ./netflix-eureka-naming-server
   - docker push $EUREKA
   
   # Zuul Gateway Server
   - export GATEWAY=continuestudying/limits-gateway
   - docker build -t $GATEWAY ./netflix-zuul-api-gateway-server
   - docker push $GATEWAY   
   
   # Limits Service
   - export LIMITS=continuestudying/limits-limits
   - docker build -t $LIMITS ./limits-service
   - docker push $LIMITS
   
   # Exchange Service   
   - export EXCHANGE=continuestudying/limits-exchange
   - docker build -t $EXCHANGE ./currency-exchange-service
   - docker push $EXCHANGE
   
   # Conversion Service
   - export CONVERSION=continuestudying/limits-conversion
   - docker build -t $CONVERSION ./currency-conversion-service
   - docker push $CONVERSION
   
deploy:
   provider: elasticbeanstalk
   region: us-east-2
   app: limits-application
   env: LimitApplication-env
   bucket_name: elasticbeanstalk-us-east-2-572689041991
   bucket_path: limits-docker
   on:
      branch: master
   access_key_id:
      secure: $AWS_ACCESS_KEY 
   secret_access_key:
      secure: $AWS_SECRET_KEY
   